### ISSUE TITLE
Tá errado de novo!

### ISSUE THREAD

**Issue by igorfv** [guicheffer/temwhats.com#5]
@guicheffer arruma!

**Comment by guicheffer** [comment]
ROFLOL

we're working on it!

**Comment by guicheffer** [comment]
ops

**Comment by igorfv** [comment]
Que nervoso com esse site TD errado

**Comment by guicheffer** [comment]
CALMA JA TAMO CORRIGINDO SR. LOGO O WHATS ESTARA DISPONIVEU

**Comment by igorfv** [comment]
eu não pago minha internet pra ficar sem saber se realmente tem whats ou não!

**Comment by igorfv** [comment]
fechando pq parece que finalmente arrumaram
